Repository woowa-techcamp-2022/web-moneybook-5, pull requests merged in 2022-07, with the labels that each got.

#2 피그마 디자인 참고 공통 색상, 아이콘 추출
  client/src/assets/calendar_icon.svg
  client/src/assets/chart_icon.svg
  client/src/assets/check_icon.svg
  client/src/assets/large_check_active.svg
  client/src/assets/large_check_default.svg
  client/src/assets/small_check_active.svg
  client/src/assets/small_check_default.svg
  client/src/assets/text_icon.svg
  client/src/styles/common.css
Labels: design

#19 백엔드 API 템플릿 구현
  server/package-lock.json
  server/package.json
  server/src/api/history/history.ctrl.js
  server/src/api/history/index.js
  server/src/api/history/middleware/history_middleware.js
  server/src/api/index.js
  server/src/api/payment_method/index.js
  server/src/api/payment_method/payment_method.ctrl.js
  server/src/app.js
  server/src/mock/mock_generator.js
Labels: feature, backend

#25 거래내역 리스트 컴포넌트 필터 기능 구현
  client/src/js/components/HistoryList.js
  client/src/styles/main.css
Labels: feature, frontend, design

#26 거래내역 아이템 마크업, 디자인
  client/src/js/components/HistoryList.js
  client/src/js/constants/category.js
  client/src/styles/common.css
  client/src/styles/main.css
  client/src/styles/reset.css
Labels: frontend, design

#29 DAO 구조 및 인터페이스 구현
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/constant/category.js
  server/src/db/DAO/history_DAO.js
  server/src/db/DAO/payment_method_DAO.js
  server/src/db/loader.js
  server/src/db/repository/category.js
  server/src/db/repository/history.js
  server/src/db/repository/payment_method.js
  server/src/utils/data_transformer.js
Labels: feature, backend

#30 refactor: DAO 오브젝트를 export 하도록 변경
  server/src/api/history/history.ctrl.js
  server/src/db/DAO/history_DAO.js
  server/src/db/DAO/payment_method_DAO.js
Labels: refactor, backend

#33 거래내역 추가 폼 구현
  client/src/js/api/request.js
  client/src/js/components/HistoryForm.js
  client/src/js/constants/history.js
  client/src/js/index.js
  client/src/js/pages/home.js
  client/src/js/store/action.js
  client/src/js/store/reducer.js
  client/src/js/utils/input_value_transformer.js
  client/src/styles/history_form.css
  client/src/styles/main.css
  server/src/api/category/category.ctrl.js
  server/src/api/category/index.js
  server/src/api/index.js
  server/src/api/payment_method/payment_method.ctrl.js
  server/src/db/DAO/category_DAO.js
Labels: feature, frontend, design

#34 원형 차트 구현
  client/package-lock.json
  client/package.json
  client/src/js/components/Donut.js
  client/src/js/constants/colors.js
  client/src/js/index.js
  client/src/js/pages/analytics.js
  client/src/js/utils/history.js
  client/src/styles/Donut.css
  client/src/styles/common.scss
  client/src/styles/reset.css
  client/webpack.config.js
Labels: feature, frontend, design

#35 결제 수단 추가, 삭제 모달 구현
  client/src/js/api/request.js
  client/src/js/components/HistoryForm.js
  client/src/js/components/PaymentMethodModal.js
  client/src/js/constants/payment_method.js
  client/src/js/index.js
  client/src/js/store/action.js
  client/src/js/store/reducer.js
  client/src/styles/PaymentMethodModal.css
  server/src/api/payment_method/payment_method.ctrl.js
  server/src/db/DAO/common_DAO.js
  server/src/db/DAO/payment_method_DAO.js
Labels: feature, frontend, backend, design

#36 fix: 금액 인풋 변환 메소드에서 import 경로 수정
  client/src/js/utils/input_value_transformer.js
Labels: bug, frontend

#45 CI/CD 환경 구성
  .github/workflows/deploy.yml
  client/package-lock.json
  client/package.json
  client/src/js/api/request.js
  client/webpack.config.js
  server/package.json
Labels: feature

#46 라인 차트 구현
  client/src/js/api/request.js
  client/src/js/components/Donut.js
  client/src/js/components/LineChart.js
  client/src/js/constants/line_chart.js
  client/src/js/index.js
  client/src/js/utils/history.js
  client/src/styles/LineChart.css
  server/src/api/history/history.ctrl.js
  server/src/db/DAO/history_DAO.js
Labels: feature, frontend, backend, design

#48 날짜 한국에 맞게 변경
  client/src/js/components/HistoryForm.js
  server/src/db/DAO/history_DAO.js
  server/src/utils/data_transformer.js
Labels: bug, frontend, backend

#53 통계 페이지 하단 리스트 렌더링
  client/src/js/components/HistoryContainer.js
  client/src/js/components/HistoryForm.js
  client/src/js/components/HistoryList.js
  client/src/js/components/LineChart.js
  client/src/js/pages/home.js
  client/src/js/utils/history.js
  client/src/styles/LineChart.css
Labels: feature, frontend

#57 컴포넌트 구조 및 라우터 리팩토링
  client/src/js/components/Analytics.js
  client/src/js/components/Calender.js
  client/src/js/components/Donut.js
  client/src/js/components/Header.js
  client/src/js/components/HistoryContainer.js
  client/src/js/components/HistoryForm.js
  client/src/js/components/HistoryList.js
  client/src/js/components/LineChart.js
  client/src/js/components/Main.js
  client/src/js/core/Component.js
  client/src/js/core/router.js
  client/src/js/custom_elements/CustomLink.js
  client/src/js/index.js
  client/src/js/pages/404.js
  client/src/js/pages/analytics.js
  client/src/js/pages/calendar.js
  client/src/js/pages/home.js
  client/src/js/store/reducer.js
  client/src/js/utils/history.js
  client/src/styles/Analytics.css
  client/src/styles/HistoryContainer.css
  client/src/styles/HistoryForm.css
Labels: refactor, frontend

#58 로딩 인디케이터 구현
  client/src/js/components/Analytics.js
  client/src/js/components/Header.js
  client/src/js/components/HistoryForm.js
  client/src/js/components/PaymentMethodModal.js
  client/src/js/components/commons/Loading.js
  client/src/js/index.js
  client/src/js/store/action.js
  client/src/js/store/reducer.js
  client/src/js/utils/request_loader.js
  client/src/styles/Loading.css
Labels: feature, frontend, design

#59 거래내역 컴포넌트 수정, 삭제 기능 구현
  client/src/js/api/history.js
  client/src/js/components/HistoryContainer.js
  client/src/js/components/HistoryForm.js
  client/src/js/components/HistoryList.js
  client/src/js/components/Modal.js
  client/src/js/constants/modal.js
  client/src/js/index.js
  client/src/js/store/action.js
  client/src/js/store/reducer.js
  client/src/js/utils/history.js
  client/src/styles/HistoryContainer.css
  client/src/styles/HistoryForm.css
  client/src/styles/Modal.css
  client/src/styles/common.scss
  server/src/api/history/history.ctrl.js
Labels: feature, refactor, frontend, backend

#61 도넛, 라인 차트 애니메이션 구현
  client/src/js/components/Analytics.js
  client/src/js/components/Donut.js
  client/src/js/components/LineChart.js
  client/src/js/constants/donut_chart.js
  client/src/js/constants/line_chart.js
  client/src/styles/Analytics.css
  client/src/styles/LineChart.css
Labels: feature, frontend, design

#62 결제 수단 추가, 삭제 시 기존 상태 유지
  client/src/js/components/HistoryForm.js
  client/src/js/components/HistoryFormDropdown.js
  client/src/js/core/Component.js
  client/src/styles/HistoryForm.css
Labels: feature, refactor, frontend

#64 year, month에 따라 페이지를 라우팅하도록 개선
  client/src/js/components/Header.js
  client/src/js/core/router.js
  client/src/js/index.js
Labels: feature, frontend

#65 UX 개선 및 잔버그 수정
  client/src/js/components/Analytics.js
  client/src/js/components/HistoryForm.js
  client/src/js/components/HistoryList.js
  client/src/styles/HistoryContainer.css
  client/src/styles/common.scss
Labels: bug, frontend

#66 거래 내역 날짜별 hash 링크로 스크롤 이동 기능 구현
  client/src/js/components/Calender.js
  client/src/js/components/Header.js
  client/src/js/components/HistoryList.js
  client/src/js/components/PaymentMethodModal.js
  client/src/js/constants/icons.js
  client/src/js/core/router.js
  client/src/js/custom_elements/CustomLink.js
  client/src/js/index.js
  client/src/js/utils/move_scroll.js
  client/src/js/utils/url_path.js
  client/src/styles/Calendar.css
  client/src/styles/HistoryContainer.css
  client/src/styles/common.scss
Labels: feature, frontend

#67 fix: 404 페이지에서 홈으로 가기 버튼을 누르면 거래 내역이 나오지 않는 버그 해결
  client/src/js/pages/404.js
Labels: bug, frontend
